# File notification configuration for logging remote work days
- platform: file
  name: remote_work_log
  filename: "/config/text_files/{{ now().year }}_working_from_home.txt"
  
- platform: group
  name: notifications
  services:
    - service: mobile_app_sm_s9060
