# Loads default set of integrations. Do not remove.
default_config:

#folder_watcher:
  #- folder: /media/
  
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include custom_sensor.yaml
notify: !include notifications.yaml
python_script: !include_dir_merge_named python_scripts
shell_command: !include shell_commands.yaml
rest_command: !include custom_command.yaml


recorder:
  exclude:
    entities:
      - switch.zigbee2mqtt_bridge_permit_join
      - select.zigbee2mqtt_bridge_log_level
      - sensor.zigbee2mqtt_bridge_version
      - automation.refresh_toothbrush_tracker
      - sensor.lucifer_activewindow_filtered
      - sensor.datamars_activewindow_filtered
      - sensor.lucifer_activewindow
      - sensor.datamars_activewindow

logger:
  default: warning
  logs:
    custom_components.streamdeck: error

logbook:
  exclude:
    entities:
      - automation.refresh_toothbrush_tracker
      - sensor.lucifer_activewindow_filtered
      - sensor.datamars_activewindow_filtered
      - sensor.lucifer_activewindow
      - sensor.datamars_activewindow

homeassistant:
  customize:
    zone.home:
      radius: 15
  allowlist_external_dirs:
    - '/config/messages'
    - '/config/text_files'
    - '/media/'
  

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: IE

media_player:
  - platform: universal
    name: universal_player
    children:
      - media_player.hugh_room_stereo
  
bluetooth:

browser_mod:
  devices:
    hugh-phone-browser:
      name: hugh_phone_browser


