# Group notification configuration (if you have multiple notification services)
- platform: group
  name: notifications
  services:
    - service: mobile_app_sm_s9060
      data:
        message: "Notification to mobile app"

# File notification configuration for logging remote work days
- platform: file
  name: remote_work_log
  filename: "/config/text_files/{{ now().year }}_working_from_home.txt"

# SMTP notification configuration for email notifications
- platform: smtp
  name: hugh_email
  server: smtp.gmail.com
  port: 587
  sender: hughhomeassistant90@gmail.com
  encryption: starttls
  username: hughhomeassistant90@gmail.com
  password: qltf insk pzyn ggto
  recipient: hughodwyer90@gmail.com
  sender_name: "Home Assistant"
