substitutions:
  name: everything-presence-one-d719b0
  friendly_name: Everything Presence One
packages:
  Everything Smart Technology.Everything Presence One: github://everythingsmarthome/everything-presence-one/everything-presence-one-beta-ble.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: zV7J3pM5yzYSxIjnNx++sOOXjDgeAD0Lcge8xaH1SDo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
