binary_sensor:
  - platform: template
    sensors:
      living_room_occupancy_scene:
        friendly_name: "Living Room Occupancy Scene Saved"
        unique_id: "living_room_occupancy_scene_saved_sensor"
        device_class: occupancy
        value_template: "{{ is_state('input_boolean.living_room_occupancy_scene_saved', 'on') }}"
        icon_template: >
          {% if is_state('input_boolean.living_room_occupancy_scene_saved', 'on') %}
            mdi:check-circle
          {% else %}
            mdi:close-circle
          {% endif %}
