- platform: template
  sensors:
    living_room_occupancy_scene:
      friendly_name: "Living Room Occupancy Scene Saved"
      unique_id: "living_room_occupancy_scene_saved_sensor"
      device_class: occupancy
      value_template: "{{ is_state('input_boolean.living_room_occupancy_scene_saved', 'on') }}"
      icon_template: >
        {% if is_state('input_boolean.living_room_occupancy_scene_saved', 'on') %}
          mdi:check-circle
        {% else %}
          mdi:close-circle
        {% endif %}
  
    snake_plant_growing_season:
      friendly_name: "Snake Plant Growing Season"
      unique_id: "snake_plant_growing_season_sensor"
      device_class: season
      value_template: "{{ now().month >= 3 and now().month <= 9 }}"
      icon_template: >
        {% if now().month >= 3 and now().month <= 9 %}
          mdi:leaf
        {% else %}
          mdi:snowflake
        {% endif %}
