esphome:
  name: esphome-web-ab1d70
  friendly_name: IR Receiver
  compile_process_limit: 2

  on_boot:
    priority: 900
    then:
      - lambda: |-
          id(button_debouncer) = new esphome::Component();

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  logs:
    sensor: ERROR
    esp32_ble_tracker: NONE
    binary_sensor: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.140
    gateway: 192.168.0.1
    subnet: 255.255.255.0

ota:
  platform: esphome

safe_mode:
  reboot_timeout: 10min
  num_attempts: 5

api:
  encryption:
    key: !secret ir_receiver_api


#####################################
# BLE SECTION — unchanged
#####################################

globals:
  - id: phone_rssi_raw
    type: int
    initial_value: '-127'

  - id: last_seen
    type: uint32_t
    initial_value: '0'

  - id: ir_last_press
    type: uint32_t
    initial_value: '0'

  # NEW: callback component for delayed OFF
  - id: button_debouncer
    type: esphome::Component*
    initial_value: 'nullptr'

esp32_ble_tracker:
  on_ble_advertise:
    - then:
        - lambda: |-
            if (x.get_ibeacon().has_value()) {
              auto beacon = x.get_ibeacon().value();

              if (
                beacon.get_uuid().to_string() == "52B58D22-8618-4072-9576-A021887EA7BD" &&
                beacon.get_major() == 100 &&
                beacon.get_minor() == 1
              ) {
                id(phone_rssi_raw) = x.get_rssi();
                id(last_seen) = id(esphome::millis)();
              }
            }

sensor:
  - platform: template
    id: phone_ble_rssi
    name: "Phone BLE RSSI"
    unit_of_measurement: "dBm"
    update_interval: 5s
    accuracy_decimals: 0
    lambda: |-
      const uint32_t timeout = 60000;
      if (id(esphome::millis)() - id(last_seen) > timeout) {
        return NAN;
      }
      return id(phone_rssi_raw);


#####################################
# IR SECTION — NEC → binary_sensor pulses
#####################################

# ==========================
# ✅ IR SECTION (FULL + BEST VERSION)
# ==========================

remote_receiver:
  pin:
    number: 13
    inverted: true
    mode: INPUT_PULLUP
  dump: nec

binary_sensor:
  - platform: remote_receiver
    name: "Typhoon Power"
    nec:
      address: 0x97E8
      command: 0xFE01
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Mute"
    nec:
      address: 0x97E8
      command: 0xE01F
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Volume Down"
    nec:
      address: 0x97E8
      command: 0xEC13
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Volume Up"
    nec:
      address: 0x97E8
      command: 0xEA15
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Woofer Up"
    nec:
      address: 0x97E8
      command: 0xED12
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Woofer Down"
    nec:
      address: 0x97E8
      command: 0xE916
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Rear Up"
    nec:
      address: 0x97E8
      command: 0xFD02
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Rear Down"
    nec:
      address: 0x97E8
      command: 0xFA05
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Center Up"
    nec:
      address: 0x97E8
      command: 0xFC03
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Center Down"
    nec:
      address: 0x97E8
      command: 0xF906
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Front Up"
    nec:
      address: 0x97E8
      command: 0xFB04
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Front Down"
    nec:
      address: 0x97E8
      command: 0xF807
    filters:
      - delayed_off: 200ms

  - platform: remote_receiver
    name: "Typhoon Reset"
    nec:
      address: 0x97E8
      command: 0xF609
    filters:
      - delayed_off: 200ms
