packages:
  brush_1: !include /config/sonicare.yaml

esphome:
  name: pressure
  friendly_name: Pressure
  compile_process_limit: 1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable BLE support
esp32_ble_tracker:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none  # Recommended for stable BLE
  manual_ip:
    static_ip: 192.168.0.201
    gateway: 192.168.0.1
    subnet: 255.255.255.0

logger:
  level: WARN

api:
  encryption:
    key: !secret pressure_api

ota:

captive_portal:


