esphome:
  name: pressure
  friendly_name: Pressure
  compile_process_limit: 1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable BLE support
esp32_ble_tracker:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none  # Recommended for stable BLE
  manual_ip:
    static_ip: 192.168.0.201
    gateway: 192.168.0.1
    subnet: 255.255.255.0

logger:
  level: WARN

api:
  encryption:
    key: !secret pressure_api

ota:

captive_portal:

# GPIO-based pressure sensors
binary_sensor:
  - platform: gpio
    pin:
      number: 13
      inverted: true
      mode: INPUT_PULLUP
    name: Rug Sensor
    device_class: occupancy
    filters:
      - delayed_on: 0s
      - delayed_off: 5s

  - platform: gpio
    pin:
      number: 15
      inverted: true
      mode: INPUT_PULLUP
    name: Bed Sensor
    device_class: occupancy
    filters:
      - delayed_on: 2s
      - delayed_off: 2s

# Sonicare toothbrush BLE integration
packages:
  brush_1:
    <<: !include_with_vars ../sonicare.yaml
    vars:
      brush_mac: "24:E5:AA:5C:A8:A0"
      brush_id: "hugh_toothbrush"
      brush_name: "Hugh Toothbrush"
