ble_client:
  mac_address: "24:E5:AA:5C:A8:A0"
  id: hugh_toothbrush
  name: "Hugh Toothbrush"
  auto_connect: true
  on_connect:
    then:
      - lambda: |-
          id(hugh_toothbrush_connected) = true;
          ESP_LOGD("ble_client_lambda", "Connected to Hugh Toothbrush");
          id(hugh_toothbrush)->pair();
          id(hugh_toothbrush_toothbrush_battery_value).set_update_interval(15000);
          id(hugh_toothbrush_toothbrush_battery_value).call_setup();
          id(hugh_toothbrush_toothbrush_head_nfc).set_update_interval(10000);
          id(hugh_toothbrush_toothbrush_head_nfc).call_setup();
          id(hugh_toothbrush_toothbrush_head_id).set_update_interval(11000);
          id(hugh_toothbrush_toothbrush_head_id).call_setup();
          id(hugh_toothbrush_toothbrush_strength).set_update_interval(10000);
          id(hugh_toothbrush_toothbrush_strength).call_setup();

  on_disconnect:
    then:
      - lambda: |-
          id(hugh_toothbrush_connected) = false;
          ESP_LOGD("ble_client_lambda", "Disconnected from Hugh Toothbrush");
          id(hugh_toothbrush_toothbrush_battery_value).set_update_interval(4294967295);
          id(hugh_toothbrush_toothbrush_battery_value).call_setup();
          id(hugh_toothbrush_toothbrush_head_nfc).set_update_interval(4294967295);
          id(hugh_toothbrush_toothbrush_head_nfc).call_setup();
          id(hugh_toothbrush_toothbrush_head_id).set_update_interval(4294967295);
          id(hugh_toothbrush_toothbrush_head_id).call_setup();
          id(hugh_toothbrush_toothbrush_strength).set_update_interval(4294967295);
          id(hugh_toothbrush_toothbrush_strength).call_setup();

globals:
  - id: hugh_toothbrush_connected
    type: bool
    restore_value: no
    initial_value: "false"

binary_sensor:
  - platform: template
    name: "Hugh Toothbrush Connection"
    id: hugh_toothbrush_ble_connection
    icon: "mdi:bluetooth-connect"
    lambda: |-
      return id(hugh_toothbrush_connected);
    device_class: connectivity

sensor:
  - platform: ble_client
    ble_client_id: hugh_toothbrush
    id: hugh_toothbrush_toothbrush_battery_value
    name: "Hugh Toothbrush Battery"
    type: characteristic
    service_uuid: 180F
    characteristic_uuid: 2A19
    notify: true
    update_interval: never
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: battery

  - platform: ble_client
    ble_client_id: hugh_toothbrush
    id: hugh_toothbrush_toothbrush_active_seconds
    name: "Hugh Toothbrush Active Time"
    type: characteristic
    service_uuid: 477ea600-a260-11e4-ae37-0002a5d50002
    characteristic_uuid: 477ea600-a260-11e4-ae37-0002a5d54090
    notify: true
    update_interval: never
    accuracy_decimals: 0
    unit_of_measurement: s

  - platform: ble_client
    ble_client_id: hugh_toothbrush
    id: hugh_toothbrush_toothbrush_state_id
    name: "Hugh Toothbrush status id"
    type: characteristic
    service_uuid: 477ea600-a260-11e4-ae37-0002a5d50001
    characteristic_uuid: 477ea600-a260-11e4-ae37-0002a5d54010
    notify: true
    update_interval: never
    internal: true
    on_value:
      then:
        - component.update: hugh_toothbrush_toothbrush_state

  - platform: ble_client
    ble_client_id: hugh_toothbrush
    id: hugh_toothbrush_toothbrush_mode_id
    name: "Hugh Toothbrush mode id"
    type: characteristic
    service_uuid: 477ea600-a260-11e4-ae37-0002a5d50002
    characteristic_uuid: 477ea600-a260-11e4-ae37-0002a5d54080
    notify: true
    update_interval: never
    internal: true
    on_value:
      then:
        - component.update: hugh_toothbrush_toothbrush_mode

  - platform: ble_client
    ble_client_id: hugh_toothbrush
    id: hugh_toothbrush_toothbrush_head_id
    name: "Hugh Toothbrush head id"
    type: characteristic
    service_uuid: 477ea600-a260-11e4-ae37-0002a5d50006
    characteristic_uuid: 477ea600-a260-11e4-ae37-0002a5d54220
    notify: true
    update_interval: never
    internal: true
    on_value:
      then:
        - component.update: hugh_toothbrush_toothbrush_head

  - platform: ble_client
    ble_client_id: hugh_toothbrush
    id: hugh_toothbrush_toothbrush_head_nfc
    name: "Hugh Toothbrush head nfc"
    type: characteristic
    service_uuid: 477ea600-a260-11e4-ae37-0002a5d50006
    characteristic_uuid: 477ea600-a260-11e4-ae37-0002a5d542a0
    notify: true
    update_interval: never
    internal: true
    on_value:
      then:
        - component.update: hugh_toothbrush_toothbrush_head

  - platform: ble_client
    ble_client_id: hugh_toothbrush
    id: hugh_toothbrush_toothbrush_strength
    icon: "mdi:toothbrush-electric"
    name: "Hugh Toothbrush Strength"
    type: characteristic
    service_uuid: 477ea600-a260-11e4-ae37-0002a5d50002
    characteristic_uuid: 477ea600-a260-11e4-ae37-0002a5d540b0
    lambda: |-
      return (float(x[0]) + 1);
    notify: true
    update_interval: never

text_sensor:
  - platform: template
    name: "Hugh Toothbrush State"
    id: hugh_toothbrush_toothbrush_state
    icon: "mdi:toothbrush-electric"
    update_interval: never
    lambda: |-
      if (id(hugh_toothbrush_toothbrush_state_id).state == 0) {
        return "Off";
      } else if (id(hugh_toothbrush_toothbrush_state_id).state == 1) {
        return "Standby";
      } else if (id(hugh_toothbrush_toothbrush_state_id).state == 2) {
        return "Run";
      } else if (id(hugh_toothbrush_toothbrush_state_id).state == 3) {
        return "Charge";
      } else if (id(hugh_toothbrush_toothbrush_state_id).state == 5) {
        return "Shutdown";
      } else if (id(hugh_toothbrush_toothbrush_state_id).state == 6) {
        return "Validate";
      } else if (id(hugh_toothbrush_toothbrush_state_id).state == 7) {
        return "LightsOut";
      } else {
        return "";
      }

  - platform: template
    name: "Hugh Toothbrush Mode"
    id: hugh_toothbrush_toothbrush_mode
    icon: "mdi:toothbrush-electric"
    update_interval: never
    lambda: |-
      if (id(hugh_toothbrush_toothbrush_mode_id).state == 0) {
        return "Clean";
      } else if (id(hugh_toothbrush_toothbrush_mode_id).state == 1) {
        return "White+";
      } else if (id(hugh_toothbrush_toothbrush_mode_id).state == 2) {
        return "Gum Health";
      } else if (id(hugh_toothbrush_toothbrush_mode_id).state == 3) {
        return "Deep Clean+";
      } else {
        return "";
      }

  - platform: template
    name: "Hugh Toothbrush Head"
    id: hugh_toothbrush_toothbrush_head
    icon: "mdi:toothbrush-electric"
    update_interval: never
    lambda: |-
      if (id(hugh_toothbrush_toothbrush_head_nfc).state == 1) {
        if (id(hugh_toothbrush_toothbrush_head_id).state == 0) {
          return "Adaptive Clean";
        } else if (id(hugh_toothbrush_toothbrush_head_id).state == 1) {
          return "Adaptive White";
        } else if (id(hugh_toothbrush_toothbrush_head_id).state == 2) {
          return "Tongue Care";
        } else if (id(hugh_toothbrush_toothbrush_head_id).state == 3) {
          return "Adaptive Gums";
        } else {
          return "Unknown";
        }
      } else if (id(hugh_toothbrush_toothbrush_head_nfc).state == 0) {
        return "N/A";
      } else {
        return "";
      }
